index:
    path:     /
    defaults: { _controller: AppBundle:Front:index }
contacts:
    path:     /contacts
    defaults: { _controller: AppBundle:Front:contacts }
macine:
    path:     /machine/{id}
    defaults: { _controller: AppBundle:Machine:show }
article:
    path:     /news/article/{id}
    defaults: { _controller: AppBundle:News:show }
news:
    path:     /news
    defaults: { _controller: AppBundle:News:news }
about:
    path:     /about
    defaults: { _controller: AppBundle:Front:about }
catalog:
    path:     /catalog
    defaults: { _controller: AppBundle:Front:catalog }